### ISSUE TITLE
Remove main links from navigation bar

### ISSUE THREAD

**Issue by atla5** [amk5401/CommunityCareHub#14]
Should not list loved one's portal or patient profile on the navigation bar.
- instead take care of that on the login screen.
- navbar should only list the logo with the navbar
  - (consider breadcrumbs for next release?)

**Comment by amk5401** [comment]
Fixed in commit: 4b2fe0593f31468611baaf2be8f23dd811809d48
It is not done well at all, but I think it still looks the way we want it too.

Also added a logout button
