### ISSUE TITLE
Clicking on "Someone Else" brings you to Carlu's Patient Profile

### ISSUE THREAD

**Issue by atla5** [amk5401/CommunityCareHub#15]
- [x] rename "Someone Else" to Carlo
- [ ] fix it so that clicking on him brings you to -his- profile.

**Comment by gcarvelli** [comment]
I don't see this as a bug. We're not implementing the whole system, we just need the patient list to redirect to the patient profile.

**Comment by atla5** [comment]
i get that. just thought it might be a point of confusion/a bump in the demo.

**Comment by atla5** [comment]
agree that it's not worth fixing for the demo.
