### ISSUE TITLE
Add help modal/tooltip to each page to describe its purpose

### ISSUE THREAD

**Issue by atla5** [amk5401/CommunityCareHub#28]
It would be helpful to have a modal describing the purpose of each page in the form of a '?' on the top nav bar. 

We could talk about that one heuristic and everything. it's not really been a problem for any of our users, though.

![image](https://cloud.githubusercontent.com/assets/5565284/14942484/1d83befe-0f8c-11e6-8354-93289eab5e85.png)

**Comment by amk5401** [comment]
Fixed in commit 624e2b0c41a2f13ac6d2cd3bf15f1772e104ef03 currently still on the dev branch
