### ISSUE TITLE
Increase Text Size to improve visibility

### ISSUE THREAD

**Issue by atla5** [amk5401/CommunityCareHub#34]
universally, but especially on the tab names and time readouts.

**Comment by atla5** [comment]
using `<h4>` tags: ![cch-navbar-h4](https://cloud.githubusercontent.com/assets/5565284/15047641/d0679f84-12b3-11e6-90ae-5f7edba8fbe4.PNG)

using `<b>` tags: ![cch-navbar-bold](https://cloud.githubusercontent.com/assets/5565284/15047642/d06da082-12b3-11e6-9142-25b91a2b2a73.PNG)

what do you think?

**Comment by gcarvelli** [comment]
I think the h4's look a little cleaner
